name = "cloudflare-workers-example"

main = "./dist/cloudflare/index.js"
workers_dev = true
no_bundle = true
compatibility_date = "2023-04-20"
compatibility_flags = [ "nodejs_compat" ]

[site]
bucket = "./dist/cloudflare/bucket"

[env.staging]
kv_namespaces = [
  { binding = "kvMain", id = "aea172d2e5f44bd399f8d334a4af8694" }
]

[env.production]
kv_namespaces = [
  { binding = "kvMain", id = "aea172d2e5f44bd399f8d334a4af8694" }
]
