name = "cloudflare-workers-example"

main = "./dist/cloudflare/index.js"
assets = "./dist/cloudflare/bucket"
workers_dev = true
# some worker api requires extra module to be injected during bundle e.g. https://github.com/cloudflare/workers-sdk/blob/5a74cb559611b1035fe97ebbe870d7061f3b41d0/packages/wrangler/src/deployment-bundle/bundle.ts#L298
no_bundle = false
compatibility_date = "2023-04-20"
compatibility_flags = [ "nodejs_compat" ]

# npx wrangler kv:namespace create kv
[[kv_namespaces]]
binding = "kv"
id = "aea172d2e5f44bd399f8d334a4af8694" # same as staging

[[env.staging.kv_namespaces]]
binding = "kv"
id = "aea172d2e5f44bd399f8d334a4af8694"

[[env.preview.kv_namespaces]]
binding = "kv"
id = "__dummy"
preview_id = "ede98539b84a411eb34ba33c9cab2ef6"

# npx wrangler d1 create demo
[[d1_databases]]
binding = "db"
database_name = "demo"
database_id = "b7ae526e-5a2b-4c16-8d7d-4a5983c4f1f1" # same as staging

[[env.staging.d1_databases]]
binding = "db"
database_name = "demo"
database_id = "b7ae526e-5a2b-4c16-8d7d-4a5983c4f1f1"

[[env.preview.d1_databases]]
binding = "db"
database_name = "demo"
database_id = "__dummy"
preview_database_id = "demo-preview" # .wrangler/state/v3/d1/demo-preview/db.sqlite
