name = "cloudflare-workers-example"

workers_dev = true
main = "./dist/cloudflare/index.js"
compatibility_date = "2023-04-20"

[site]
bucket = "./dist/cloudflare/bucket"

[env.staging]

[env.production]
